macos_arm64_task:
  name: Build macOS arm64 wheels.
  only_if: $CIRRUS_TAG =~ 'v.*' && $CIRRUS_REPO_OWNER == 'cmake-wheel'
  environment:
    TWINE_PASSWORD: ENCRYPTED[8c0d0286cd8c18e23e5b0a624bd7ae71a7759141e28fc77d9f3322ecf3a2fe99288d46a047de832fb5569df02a043554]
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode
  env:
    CIRRUS_CLONE_SUBMODULES: true
    CIBW_REPAIR_WHEEL_COMMAND: ""
    CIBW_SKIP: "cp38-*"
    PATH: /opt/homebrew/opt/python@3.10/bin:$PATH
  install_pre_requirements_script:
    - brew install python@3.10
    - ln -s python3 /opt/homebrew/opt/python@3.10/bin/python
  install_cibuildwheel_script:
    - python -m pip install -U pip
    - python -m pip install cibuildwheel twine
  run_cibuildwheel_script:
    - cibuildwheel
  publish_script:
    - python -m twine upload -u __token__ wheelhouse/hpp_fcl*.whl
  wheels_artifacts:
    path: "wheelhouse/*"
