ci:
  autoupdate_branch: devel
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.5
  hooks:
  - id: ruff
    args:
    - --fix
    - --exit-non-zero-on-fix
- repo: https://github.com/pappasam/toml-sort
  rev: v0.23.0
  hooks:
  - id: toml-sort-fix
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v18.1.3
  hooks:
  - id: clang-format
    args:
    - '--style={BasedOnStyle: Google, SortIncludes: false}'
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 24.3.0
  hooks:
  - id: black
