name: Test Wheel packaging

on: ["push", "pull_request"]

jobs:
  build:
    name: Build ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.9", "3.10", "3.11"]
        include:
          - os: "ubuntu-latest"
            python-version: "3.7"
          - os: "ubuntu-latest"
            python-version: "3.8"
          - os: "macos-10.15"
            python-version: "3.7"
          - os: "macos-10.15"
            python-version: "3.8"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: setup
        run: |
          python -m pip install -U pip
          python -m pip install wheel
      - name: build cmeel wheel
        run: python -m pip wheel -vw wh .
      - uses: actions/upload-artifact@v3
        with:
          path: wh

  test:
    needs: ["build"]
    name: Test ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/download-artifact@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: setup
        run: |
          python -m pip install -U pip
          python -m pip install wheel simple503
          python -m simple503 --sort --base-url "${{ github.workspace }}/artifact" artifact
          python -m pip install -U pip
      - name: install wheel
        run: python -m pip install -i "file:///${{ github.workspace }}/artifact" hpp-fcl
      - name: test
        run: python -c "import hppfcl; assert abs(hppfcl.Capsule(2, 3).computeVolume() - 71.2094334814) < 1e-7"
        env:
          PYTHONWARNINGS: error
